=== SuzdalenkoAlexey/_instituto_/C2/LMSGI/LMSGI04 dtd/Actividad3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.ejemplo.com/jugadores"
           xmlns="http://www.ejemplo.com/jugadores"
           elementFormDefault="qualified">

  <xs:annotation>
    <xs:documentation xml:lang="es">
      Schema para el documento jugadores.xml
      Fecha de creaci√≥n: 2024-03-08
      Autores: [Alexey Suzdalenko]
      Curso Escolar: [2024/1 curso]
    </xs:documentation>
  </xs:annotation>

  <!-- Ssimples -->
  <xs:simpleType name="TipoId">
    <xs:restriction base="xs:string">
      <xs:pattern value="J[0-9]{4}/[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TipoFecha">
    <xs:restriction base="xs:date"/>
  </xs:simpleType>

  <xs:simpleType name="TipoAltura">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="150"/>
      <xs:maxInclusive value="210"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TipoPeso">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="60"/>
      <xs:maxInclusive value="90"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TipoEstadistica">
    <xs:restriction base="xs:positiveInteger"/>
  </xs:simpleType>

  <xs:simpleType name="TipoYear">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="2000"/>
      <xs:maxInclusive value="2100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TipoPosicion">
    <xs:restriction base="xs:string">
      <xs:enumeration value="portero"/>
      <xs:enumeration value="defensa"/>
      <xs:enumeration value="mediocentro"/>
      <xs:enumeration value="delantero"/>
      <xs:enumeration value="extremo"/>
      <xs:enumeration value="mediapunta"/>
      <xs:enumeration value="segundo_delantero"/>
      <xs:enumeration value="interior"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- se describe el elemento estadisticas viendo el video ASI SE ACONSEJA HACER -->
  <xs:element name="estadisticas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="partidos_jugados" type="TipoEstadistica" />
        <xs:element name="goles_anotados" type="TipoEstadistica" />
        <xs:element name="asistencias" type="TipoEstadistica" />
        <xs:element name="targetas_amarillas" type="TipoEstadistica" />
        <xs:element name="tarjetas_rojas" type="TipoEstadistica" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Elemento root -->
  <xs:element name="jugadores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="jugador" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre_jugador" type="xs:string"/>
              <xs:element name="fecha_nacimiento" type="TipoFecha"/>
              <xs:element name="nacionalidad" type="xs:string"/>
              <xs:element name="altura" type="TipoAltura"/>
              <xs:element name="peso" type="TipoPeso"/>
              <xs:element ref="estadisticas"/>                                   hay que utlizar el atributo REF !!!
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="partidos_jugados" type="TipoEstadistica"/>
                    <xs:element name="goles_anotados" type="TipoEstadistica"/>
                    <xs:element name="asistencias" type="TipoEstadistica"/>
                    <xs:element name="tarjetas_amarillas" type="TipoEstadistica"/>
                    <xs:element name="tarjetas_rojas" type="TipoEstadistica"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="equipos_anteriores">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="equipo" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre_equipo" type="xs:string"/>
                          <xs:element name="inicio" type="TipoYear"/>
                          <xs:element name="fin" type="TipoYear" minOccurs="0"/>    <xs:element name="fin" type="xs:string"/> como tendria que ser !!!
                          <xs:element name="logros">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="logro" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="titulo" type="xs:string"/>
                                      <xs:element name="veces_conquistado" type="TipoEstadistica"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="posiciones">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="principal">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="posicion" type="TipoPosicion"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="secundarias">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="posicion" type="TipoPosicion" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id_jugador" type="TipoId" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== SuzdalenkoAlexey/_instituto_/C2/LMSGI/LMSGI04/Actividad4.xml
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<jugadores xmlns="http://www.w3.org/jugadores"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="Actividad3.xsd">
<jugadores>
    <jugador id="J0001/01">
		<nombre_jugador>Lionel Messi</nombre_jugador>
        <fecha_nacimiento>1987-06-24</fecha_nacimiento>
		<nacionalidad>Argentina</nacionalidad>
        <altura>170</altura>
        <peso>72</peso>
        <estadisticas>
			<partidos_jugados>800</partidos_jugados>
            <goles_anotados>700</goles_anotados>
            <asistencias>300</asistencias>
            <tarjetas_amarillas>30</tarjetas_amarillas>
            <tarjetas_rojas>1</tarjetas_rojas>
        </estadisticas>
        <equipos_anteriores>
            <equipo>
				<nombre_equipo>FC.Barcelona</nombre_equipo>
				<inicio>2004</inicio>
				<fin>2021</fin>
                <logros>
					<logro>
						<titulo>Liga Espa√±ola</titulo>
						<veces_conquistado>10</veces_conquistado>
					</logro>
					<logro>
						<titulo>Liga Campeones de la UEFA</titulo>
						<veces_conquistado>4</veces_conquistado>
					</logro>
                </logros>
            </equipo>
            <equipo>
				<nombre_equipo>Paris Saint-Germain</nombre_equipo>
				<inicio>2021</inicio>
				<fin>2022</fin>
				<logros>
					<logro>
						<titulo>Ligue 1</titulo>
						<veces_conquistado>1</veces_conquistado>
					</logro>
                </logros>  
            </equipo>
            <equipo>
				<nombre_equipo>Inter Miami</nombre_equipo>
				<inicio>2023</inicio>
				<fin/>
                <logros/>
            </equipo>
        </equipos_anteriores>
        <posiciones>
            <principal>
                <posicion>delantero</posicion>
            </principal>
            <secundarias>
                <posicion>extremo</posicion>
                <posicion>segundo delantero</posicion>
            </secundarias>
        </posiciones>
	</jugador>
    <jugador id="J0002/01">
		<nombre_jugador>Cristiano Ronaldo</nombre_jugador>
        <fecha_nacimiento>1985-02-05</fecha_nacimiento>
        <nacionalidad>Portuguesa</nacionalidad>
        <altura>187</altura>
        <peso>83</peso>
        <estadisticas>
            <partidos_jugados>850</partidos_jugados>
            <goles_anotados>750</goles_anotados>
            <asistencias>200</asistencias>
            <tarjetas_amarillas>20</tarjetas_amarillas>
            <tarjetas_rojas>1</tarjetas_rojas>
        </estadisticas>
        <equipos_anteriores>
            <equipo>	
				<nombre_equipo>Sporting Lisboa</nombre_equipo>
				<inicio>2002</inicio>
				<fin>2003</fin>
                <logros>
					<logro>
						<titulo>Primeira Liga</titulo>
						<veces_conquistado>1</veces_conquistado>
					</logro>
					<logro>
						<titulo>Liga Campeones de la UEFA</titulo>
						<veces_conquistado>4</veces_conquistado>
					</logro>
                </logros>
            </equipo>
            <equipo>
				<nombre_equipo>Manchester United</nombre_equipo>
				<inicio>2003</inicio>
				<fin>2009</fin>
                <logros>
					<logro>
						<titulo>Premier League</titulo>
						<veces_conquistado>3</veces_conquistado>
					</logro>
					<logro>
						<titulo>Liga Campeones de la UEFA</titulo>
						<veces_conquistado>1</veces_conquistado>
					</logro>
                </logros>
            </equipo>
            <equipo>
				<nombre_equipo>Real Madrid</nombre_equipo>
				<inicio>2009</inicio>
				<fin>2018</fin>
                <logros>
					<logro>
						<titulo>Liga</titulo>
						<veces_conquistado>2</veces_conquistado>
					</logro>
					<logro>
						<titulo>Liga Campeones de la UEFA</titulo>
						<veces_conquistado>4</veces_conquistado>
					</logro>
					<logro>
						<titulo>Copa del Rey</titulo>
						<veces_conquistado>2</veces_conquistado>
					</logro>
                </logros>
            </equipo>
            <equipo>
				<nombre_equipo>Juventus</nombre_equipo>
				<inicio>2018</inicio>
				<fin>2021</fin>
                <logros>
					<logro>
						<titulo>Serie A</titulo>
						<veces_conquistado>2</veces_conquistado>
					</logro>
					<logro>
						<titulo>Supercoppa italiana</titulo>
						<veces_conquistado>1</veces_conquistado>
					</logro>
                </logros>
            </equipo>
			 <equipo>
				<nombre_equipo>Manchester United</nombre_equipo>
				<inicio>2021</inicio>
				<fin>2022</fin>
                <logros/>
            </equipo>
            <equipo>
				<nombre_equipo>Al-Nassr</nombre_equipo>
				<inicio>2022</inicio>
				<fin/>
                <logros/>
            </equipo>
        </equipos_anteriores>
        <posiciones>
            <principal>
                <posicion>delantero</posicion>
            </principal>
            <secundarias>
                <posicion>extremo</posicion>
                <posicion>segundo delantero</posicion>
            </secundarias>
        </posiciones>
    </jugador>
</jugadores>
